-- 1. Create the session_chat_messages table
CREATE TABLE IF NOT EXISTS public.session_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES public.collaborative_sessions(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable RLS
ALTER TABLE public.session_chat_messages ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies
DROP POLICY IF EXISTS "Allow participants to view chat messages" ON public.session_chat_messages;
CREATE POLICY "Allow participants to view chat messages"
ON public.session_chat_messages
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.session_participants
        WHERE session_participants.session_id = session_chat_messages.session_id
        AND session_participants.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Allow participants to send chat messages" ON public.session_chat_messages;
CREATE POLICY "Allow participants to send chat messages"
ON public.session_chat_messages
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.session_participants
        WHERE session_participants.session_id = session_chat_messages.session_id
        AND session_participants.user_id = auth.uid()
    )
);

-- 4. Create an index for faster lookups
CREATE INDEX IF NOT EXISTS idx_session_chat_messages_session_id ON public.session_chat_messages(session_id);
