-- 1. Create the main table for collaborative sessions
CREATE TABLE IF NOT EXISTS public.collaborative_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    challenge_id UUID NOT NULL,
    host_id UUID NOT NULL REFERENCES auth.users(id),
    is_active BOOLEAN DEFAULT true,
    session_state JSONB, -- Stores the shared state of the code, visualization, etc.
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create a table to track participants in each session
CREATE TABLE IF NOT EXISTS public.session_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES public.collaborative_sessions(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(session_id, user_id)
);

-- 3. Enable RLS for the tables
ALTER TABLE public.collaborative_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_participants ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for collaborative_sessions
DROP POLICY IF EXISTS "Allow authenticated users to create sessions" ON public.collaborative_sessions;
CREATE POLICY "Allow authenticated users to create sessions"
ON public.collaborative_sessions
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = host_id);

DROP POLICY IF EXISTS "Allow participants to view active sessions" ON public.collaborative_sessions;
CREATE POLICY "Allow participants to view active sessions"
ON public.collaborative_sessions
FOR SELECT
TO authenticated
USING (
    is_active = true AND
    EXISTS (
        SELECT 1
        FROM public.session_participants
        WHERE session_participants.session_id = collaborative_sessions.id -- Corrected: qualified the column name
        AND session_participants.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Allow host to update the session" ON public.collaborative_sessions;
CREATE POLICY "Allow host to update the session"
ON public.collaborative_sessions
FOR UPDATE
TO authenticated
USING (auth.uid() = host_id)
WITH CHECK (auth.uid() = host_id);

-- 5. Create Policies for session_participants
DROP POLICY IF EXISTS "Allow users to join a session (insert)" ON public.session_participants;
CREATE POLICY "Allow users to join a session (insert)"
ON public.session_participants
FOR INSERT
TO authenticated
WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
        SELECT 1
        FROM public.collaborative_sessions
        WHERE id = session_id AND is_active = true
    )
);

DROP POLICY IF EXISTS "Allow participants to view who is in the session" ON public.session_participants;
CREATE POLICY "Allow participants to view who is in the session"
ON public.session_participants
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.session_participants p2
        WHERE p2.session_id = session_participants.session_id
        AND p2.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Allow users to leave a session (delete)" ON public.session_participants;
CREATE POLICY "Allow users to leave a session (delete)"
ON public.session_participants
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 6. Add trigger for automatic timestamp updates on collaborative_sessions
DROP TRIGGER IF EXISTS update_collaborative_sessions_updated_at ON public.collaborative_sessions;
CREATE TRIGGER update_collaborative_sessions_updated_at
BEFORE UPDATE ON public.collaborative_sessions
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
