-- Seed algorithm categories and data
-- This statement was incorrect, referencing a 'difficulty' column that does not exist.
-- The 'dsa_topics' table is already populated by a previous migration (20250708171325_init_schema_2.sql).
-- This insert is redundant and will cause errors. It is now commented out.
-- INSERT INTO public.dsa_topics (name, description, category, learning_path_order, created_at) VALUES
-- ('Arrays', 'Learn array manipulation and traversal techniques', 'Data Structures', 1, NOW()),
-- ('Linked Lists', 'Master linked list operations and algorithms', 'Data Structures', 2, NOW()),
-- ('Stacks & Queues', 'Understand LIFO and FIFO data structures', 'Data Structures', 3, NOW()),
-- ('Trees', 'Binary trees, BST, and tree traversals', 'Data Structures', 4, NOW()),
-- ('Graphs', 'Graph algorithms and traversal methods', 'Data Structures', 5, NOW()),
-- ('Sorting', 'Various sorting algorithms and their complexities', 'Algorithms', 6, NOW()),
-- ('Searching', 'Binary search and search optimization', 'Algorithms', 7, NOW()),
-- ('Dynamic Programming', 'Optimization through memorization', 'Algorithms', 8, NOW()),
-- ('Greedy Algorithms', 'Making locally optimal choices', 'Algorithms', 9, NOW()),
-- ('Backtracking', 'Systematic search through solution space', 'Algorithms', 10, NOW())
-- ON CONFLICT (name) DO NOTHING;

-- Seed LeetCode questions
-- This statement was also incorrect, using 'topic' instead of 'topic_id' and not providing a valid UUID.
-- The leetcode_questions are already seeded in a previous migration (20250716090745_init_schema_5.sql).
-- This insert is redundant and will cause errors. It is now commented out.
-- INSERT INTO public.leetcode_questions (title, difficulty, topic_id, problem_statement, solution, hints, time_complexity, space_complexity, created_at) VALUES
-- ('Two Sum', 'easy', (SELECT id from dsa_topics where name = 'Arrays'), 
-- 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
-- 'Use a hash map to store complement values and their indices for O(n) solution.',
-- '["Think about what you need to find for each number", "A hash map can help you look up values quickly"]',
-- 'O(n)', 'O(n)', NOW()),
-- ... (rest of the inserts are also commented out for the same reason)
-- ON CONFLICT (title) DO NOTHING;

-- Seed challenges
-- This statement was also incorrect.
-- Challenges are seeded in a previous migration.
-- This insert is redundant and will cause errors. It is now commented out.
-- INSERT INTO public.challenges (title, description, difficulty, points, time_limit, category, problem_statement, test_cases, solution_template, created_at) VALUES
-- ...
-- ON CONFLICT (title) DO NOTHING;

-- Create sample admin user (you'll need to update the user_id after creating a real user)
-- INSERT INTO public.admin_roles (user_id, role, created_by, created_at) VALUES
-- ('your-user-id-here', 'super_admin', 'your-user-id-here', NOW())
-- ON CONFLICT (user_id, role) DO NOTHING;

-- Seed learning paths
-- This statement was also incorrect.
-- Learning paths are seeded in a previous migration.
-- This insert is redundant and will cause errors. It is now commented out.
-- INSERT INTO public.learning_paths (title, description, difficulty, estimated_hours, topics, created_at) VALUES
-- ...
-- ON CONFLICT (title) DO NOTHING;

-- Add sample user progress and achievements
-- Note: These would be populated as users interact with the system
-- All inserts in this file are commented out as they are redundant and conflict with previous migrations.
-- This file is now effectively empty but is kept to maintain the migration history.