// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lctytebgxakcztdijbxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdHl0ZWJneGFrY3p0ZGlqYnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjQ0NDgsImV4cCI6MjA2NjUwMDQ0OH0.I3cf-X6MUw4E7t6NMI-p7QiiLcvLjjNm72sePZGuUU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);